<?php

use Illuminate\Database\Seeder;
use App\Models\Tool;
use App\Models\Region;
use App\Models\Country;

class ToolCountryRegionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Tool::insert([
            ['name' => 'Agriculture Project'],
            ['name' => 'Water Project'], 
            ['name' => 'Energy Project' ], 
            ['name' => 'Natural Resource'], 
            ['name' => 'Transportation Project']]
        );

        Region::insert([
            ['id' => 8, 'name' => 'South Asia', 'region_name' => 'Asia', 'region_code' => 'AS'],
            ['id' => 13, 'name' => 'Middle East and North Africa', 'region_name' => 'Africa', 'region_code' => 'AF'], 
            ['id' => 21, 'name' => 'Europe and Central Asia' , 'region_name' => 'Europe', 'region_code' => 'EU'], 
            ['id' => 24, 'name' => 'East Asia and Pacific', 'region_name' => 'Australia', 'region_code' => 'AO'], 
            ['id' => 26, 'name' => 'Latin America and the Caribbean', 'region_name' => 'Latin America', 'region_code' => 'LA'], 
            ['id' => 47, 'name' => 'Sub-Saharan Africa', 'region_name' => 'Africa', 'region_code' => 'AF']]
        );

        $data1 = [['id' => 1, 'iso2' => 'AF', 'iso3' => 'AFG', 'name' => 'Afghanistan', 'numcode' => 4, 'region_id' => 8],
        ['id' => 2, 'iso2' => 'AX', 'iso3' => 'ALA', 'name' => 'Aland Islands', 'numcode' => 248, 'region_id' => 21],
        ['id' => 3, 'iso2' => 'AL', 'iso3' => 'ALB', 'name' => 'Albania', 'numcode' => 8, 'region_id' => 21],
        ['id' => 4, 'iso2' => 'DZ', 'iso3' => 'DZA', 'name' => 'Algeria', 'numcode' => 12, 'region_id' => 13],
        ['id' => 5, 'iso2' => 'AS', 'iso3' => 'ASM', 'name' => 'American Samoa', 'numcode' => 16, 'region_id' => 24],
        ['id' => 6, 'iso2' => 'AD', 'iso3' => 'ANDs', 'name' => 'Andorra', 'numcode' => 20, 'region_id' => 21],
        ['id' => 7, 'iso2' => 'AO', 'iso3' => 'AGO', 'name' => 'Angola', 'numcode' => 24, 'region_id' => 47],
        ['id' => 8, 'iso2' => 'AI', 'iso3' => 'AIA', 'name' => 'Anguilla', 'numcode' => 660, 'region_id' => 26],
        ['id' => 9, 'iso2' => 'AQ', 'iso3' => 'ATA', 'name' => 'Antarctica', 'numcode' => 10, 'region_id' => NULL],
        ['id' => 10, 'iso2' => 'AG', 'iso3' => 'ATG', 'name' => 'Antigua and Barbuda', 'numcode' => 28, 'region_id' => 26],
        ['id' => 11, 'iso2' => 'AR', 'iso3' => 'ARG', 'name' => 'Argentina', 'numcode' => 32, 'region_id' => 26],
        ['id' => 12, 'iso2' => 'AM', 'iso3' => 'ARM', 'name' => 'Armenia', 'numcode' => 51, 'region_id' => 21],
        ['id' => 13, 'iso2' => 'AW', 'iso3' => 'ABW', 'name' => 'Aruba', 'numcode' => 533, 'region_id' => 26],
        ['id' => 14, 'iso2' => 'AU', 'iso3' => 'AUS', 'name' => 'Australia', 'numcode' => 36, 'region_id' => 24],
        ['id' => 15, 'iso2' => 'AT', 'iso3' => 'AUT', 'name' => 'Austria', 'numcode' => 40, 'region_id' => 21],
        ['id' => 16, 'iso2' => 'AZ', 'iso3' => 'AZE', 'name' => 'Azerbaijan', 'numcode' => 31, 'region_id' => 21],
        ['id' => 17, 'iso2' => 'BS', 'iso3' => 'BHS', 'name' => 'Bahamas', 'numcode' => 44, 'region_id' => 26],
        ['id' => 18, 'iso2' => 'BH', 'iso3' => 'BHR', 'name' => 'Bahrain', 'numcode' => 48, 'region_id' => 13],
        ['id' => 19, 'iso2' => 'BD', 'iso3' => 'BGD', 'name' => 'Bangladesh', 'numcode' => 50, 'region_id' => 8],
        ['id' => 20, 'iso2' => 'BB', 'iso3' => 'BRB', 'name' => 'Barbados', 'numcode' => 52, 'region_id' => 26],
        ['id' => 21, 'iso2' => 'BY', 'iso3' => 'BLR', 'name' => 'Belarus', 'numcode' => 112, 'region_id' => 21],
        ['id' => 22, 'iso2' => 'BE', 'iso3' => 'BEL', 'name' => 'Belgium', 'numcode' => 56, 'region_id' => 21],
        ['id' => 23, 'iso2' => 'BZ', 'iso3' => 'BLZ', 'name' => 'Belize', 'numcode' => 84, 'region_id' => 26],
        ['id' => 24, 'iso2' => 'BJ', 'iso3' => 'BEN', 'name' => 'Benin', 'numcode' => 204, 'region_id' => 47],
        ['id' => 25, 'iso2' => 'BM', 'iso3' => 'BMU', 'name' => 'Bermuda', 'numcode' => 60, 'region_id' => 26],
        ['id' => 26, 'iso2' => 'BT', 'iso3' => 'BTN', 'name' => 'Bhutan', 'numcode' => 64, 'region_id' => 8],
        ['id' => 27, 'iso2' => 'BO', 'iso3' => 'BOL', 'name' => 'Bolivia', 'numcode' => 68, 'region_id' => 26],
        ['id' => 28, 'iso2' => 'BA', 'iso3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'numcode' => 70, 'region_id' => 21],
        ['id' => 29, 'iso2' => 'BQ', 'iso3' => 'BES', 'name' => 'Bonaire, Sint Eustatius and Saba', 'numcode' => 535, 'region_id' => 26],
        ['id' => 30, 'iso2' => 'BW', 'iso3' => 'BWA', 'name' => 'Botswana', 'numcode' => 72, 'region_id' => 47],
        ['id' => 31, 'iso2' => 'BV', 'iso3' => 'BVT', 'name' => 'Bouvet Island', 'numcode' => 74, 'region_id' => NULL],
        ['id' => 32, 'iso2' => 'BR', 'iso3' => 'BRA', 'name' => 'Brazil', 'numcode' => 76, 'region_id' => 26],
        ['id' => 33, 'iso2' => 'IO', 'iso3' => 'IOT', 'name' => 'British Indian Ocean Territory', 'numcode' => 86, 'region_id' => 8],
        ['id' => 34, 'iso2' => 'BN', 'iso3' => 'BRN', 'name' => 'Brunei Darussalam', 'numcode' => 96, 'region_id' => 24],
        ['id' => 35, 'iso2' => 'BG', 'iso3' => 'BGR', 'name' => 'Bulgaria', 'numcode' => 100, 'region_id' => 21],
        ['id' => 36, 'iso2' => 'BF', 'iso3' => 'BFA', 'name' => 'Burkina Faso', 'numcode' => 854, 'region_id' => 47],
        ['id' => 37, 'iso2' => 'BI', 'iso3' => 'BDI', 'name' => 'Burundi', 'numcode' => 108, 'region_id' => 47],
        ['id' => 38, 'iso2' => 'KH', 'iso3' => 'KHM', 'name' => 'Cambodia', 'numcode' => 116, 'region_id' => 24],
        ['id' => 39, 'iso2' => 'CM', 'iso3' => 'CMR', 'name' => 'Cameroon', 'numcode' => 120, 'region_id' => 47],
        ['id' => 40, 'iso2' => 'CA', 'iso3' => 'CAN', 'name' => 'Canada', 'numcode' => 124, 'region_id' => 26],
        ['id' => 41, 'iso2' => 'CV', 'iso3' => 'CPV', 'name' => 'Cape Verde', 'numcode' => 132, 'region_id' => 47],
        ['id' => 42, 'iso2' => 'KY', 'iso3' => 'CYM', 'name' => 'Cayman Islands', 'numcode' => 136, 'region_id' => 26],
        ['id' => 43, 'iso2' => 'CF', 'iso3' => 'CAF', 'name' => 'Central African Republic', 'numcode' => 140, 'region_id' => 47],
        ['id' => 44, 'iso2' => 'TD', 'iso3' => 'TCD', 'name' => 'Chad', 'numcode' => 148, 'region_id' => 47],
        ['id' => 45, 'iso2' => 'CL', 'iso3' => 'CHL', 'name' => 'Chile', 'numcode' => 152, 'region_id' => 26],
        ['id' => 46, 'iso2' => 'CN', 'iso3' => 'CHN', 'name' => 'China', 'numcode' => 156, 'region_id' => 24],
        ['id' => 47, 'iso2' => 'CX', 'iso3' => 'CXR', 'name' => 'Christmas Island', 'numcode' => 162, 'region_id' => 24],
        ['id' => 48, 'iso2' => 'CC', 'iso3' => 'CCK', 'name' => 'Cocos (Keeling) Islands', 'numcode' => 166, 'region_id' => 24],
        ['id' => 49, 'iso2' => 'CO', 'iso3' => 'COL', 'name' => 'Colombia', 'numcode' => 170, 'region_id' => 26],
        ['id' => 50, 'iso2' => 'KM', 'iso3' => 'COM', 'name' => 'Comoros', 'numcode' => 174, 'region_id' => 47],
        ['id' => 51, 'iso2' => 'CG', 'iso3' => 'COG', 'name' => 'Congo (Brazzaville)', 'numcode' => 178, 'region_id' => 47],
        ['id' => 52, 'iso2' => 'CD', 'iso3' => 'COD', 'name' => 'Congo (Kinshasa)', 'numcode' => 180, 'region_id' => 47],
        ['id' => 53, 'iso2' => 'CK', 'iso3' => 'COK', 'name' => 'Cook Islands', 'numcode' => 184, 'region_id' => 24],
        ['id' => 54, 'iso2' => 'CR', 'iso3' => 'CRI', 'name' => 'Costa Rica', 'numcode' => 188, 'region_id' => 26],
        ['id' => 55, 'iso2' => 'CI', 'iso3' => 'CIV', 'name' => 'Cote d\'Ivoire', 'numcode' => 384, 'region_id' => 47],
        ['id' => 56, 'iso2' => 'HR', 'iso3' => 'HRV', 'name' => 'Croatia', 'numcode' => 191, 'region_id' => 21],
        ['id' => 57, 'iso2' => 'CU', 'iso3' => 'CUB', 'name' => 'Cuba', 'numcode' => 192, 'region_id' => 26],
        ['id' => 58, 'iso2' => 'CW', 'iso3' => 'CUW', 'name' => 'Curacao', 'numcode' => 531, 'region_id' => 26],
        ['id' => 59, 'iso2' => 'CY', 'iso3' => 'CYP', 'name' => 'Cyprus', 'numcode' => 196, 'region_id' => 21],
        ['id' => 60, 'iso2' => 'CZ', 'iso3' => 'CZE', 'name' => 'Czech Republic', 'numcode' => 203, 'region_id' => 21],
        ['id' => 61, 'iso2' => 'DK', 'iso3' => 'DNK', 'name' => 'Denmark', 'numcode' => 208, 'region_id' => 21],
        ['id' => 62, 'iso2' => 'DJ', 'iso3' => 'DJI', 'name' => 'Djibouti', 'numcode' => 262, 'region_id' => 13],
        ['id' => 63, 'iso2' => 'DM', 'iso3' => 'DMA', 'name' => 'Dominica', 'numcode' => 212, 'region_id' => 26],
        ['id' => 64, 'iso2' => 'DO', 'iso3' => 'DOM', 'name' => 'Dominican Republic', 'numcode' => 214, 'region_id' => 26],
        ['id' => 65, 'iso2' => 'EC', 'iso3' => 'ECU', 'name' => 'Ecuador', 'numcode' => 218, 'region_id' => 26],
        ['id' => 66, 'iso2' => 'EG', 'iso3' => 'EGY', 'name' => 'Egypt', 'numcode' => 818, 'region_id' => 13],
        ['id' => 67, 'iso2' => 'SV', 'iso3' => 'SLV', 'name' => 'El Salvador', 'numcode' => 222, 'region_id' => 26],
        ['id' => 68, 'iso2' => 'GQ', 'iso3' => 'GNQ', 'name' => 'Equatorial Guinea', 'numcode' => 226, 'region_id' => 47],
        ['id' => 69, 'iso2' => 'ER', 'iso3' => 'ERI', 'name' => 'Eritrea', 'numcode' => 232, 'region_id' => 47],
        ['id' => 70, 'iso2' => 'EE', 'iso3' => 'EST', 'name' => 'Estonia', 'numcode' => 233, 'region_id' => 21],
        ['id' => 71, 'iso2' => 'ET', 'iso3' => 'ETH', 'name' => 'Ethiopia', 'numcode' => 231, 'region_id' => 47],
        ['id' => 72, 'iso2' => 'FK', 'iso3' => 'FLK', 'name' => 'Falkland Islands', 'numcode' => 238, 'region_id' => 26],
        ['id' => 73, 'iso2' => 'FO', 'iso3' => 'FRO', 'name' => 'Faroe Islands', 'numcode' => 234, 'region_id' => 21],
        ['id' => 74, 'iso2' => 'FJ', 'iso3' => 'FJI', 'name' => 'Fiji', 'numcode' => 242, 'region_id' => 24],
        ['id' => 75, 'iso2' => 'FI', 'iso3' => 'FIN', 'name' => 'Finland', 'numcode' => 246, 'region_id' => 21],
        ['id' => 76, 'iso2' => 'FR', 'iso3' => 'FRA', 'name' => 'France', 'numcode' => 250, 'region_id' => 21],
        ['id' => 77, 'iso2' => 'GF', 'iso3' => 'GUF', 'name' => 'French Guiana', 'numcode' => 254, 'region_id' => 26],
        ['id' => 78, 'iso2' => 'PF', 'iso3' => 'PYF', 'name' => 'French Polynesia', 'numcode' => 258, 'region_id' => 24],
        ['id' => 79, 'iso2' => 'TF', 'iso3' => 'ATF', 'name' => 'French Southern Territories', 'numcode' => 260, 'region_id' => NULL],
        ['id' => 80, 'iso2' => 'GA', 'iso3' => 'GAB', 'name' => 'Gabon', 'numcode' => 266, 'region_id' => 47],
        ['id' => 81, 'iso2' => 'GM', 'iso3' => 'GMB', 'name' => 'Gambia', 'numcode' => 270, 'region_id' => 47],
        ['id' => 82, 'iso2' => 'GE', 'iso3' => 'GEO', 'name' => 'Georgia', 'numcode' => 268, 'region_id' => 21],
        ['id' => 83, 'iso2' => 'DE', 'iso3' => 'DEU', 'name' => 'Germany', 'numcode' => 276, 'region_id' => 21],
        ['id' => 84, 'iso2' => 'GH', 'iso3' => 'GHA', 'name' => 'Ghana', 'numcode' => 288, 'region_id' => 47],
        ['id' => 85, 'iso2' => 'GI', 'iso3' => 'GIB', 'name' => 'Gibraltar', 'numcode' => 292, 'region_id' => 21],
        ['id' => 86, 'iso2' => 'GR', 'iso3' => 'GRC', 'name' => 'Greece', 'numcode' => 300, 'region_id' => 21],
        ['id' => 87, 'iso2' => 'GL', 'iso3' => 'GRL', 'name' => 'Greenland', 'numcode' => 304, 'region_id' => 21],
        ['id' => 88, 'iso2' => 'GD', 'iso3' => 'GRD', 'name' => 'Grenada', 'numcode' => 308, 'region_id' => 26],
        ['id' => 89, 'iso2' => 'GP', 'iso3' => 'GLP', 'name' => 'Guadeloupe', 'numcode' => 312, 'region_id' => 26],
        ['id' => 90, 'iso2' => 'GU', 'iso3' => 'GUM', 'name' => 'Guam', 'numcode' => 316, 'region_id' => 24],
        ['id' => 91, 'iso2' => 'GT', 'iso3' => 'GTM', 'name' => 'Guatemala', 'numcode' => 320, 'region_id' => 26],
        ['id' => 92, 'iso2' => 'GG', 'iso3' => 'GGY', 'name' => 'Guernsey', 'numcode' => 831, 'region_id' => 21],
        ['id' => 93, 'iso2' => 'GN', 'iso3' => 'GIN', 'name' => 'Guinea', 'numcode' => 324, 'region_id' => 47],
        ['id' => 94, 'iso2' => 'GW', 'iso3' => 'GNB', 'name' => 'Guinea-Bissau', 'numcode' => 624, 'region_id' => 47],
        ['id' => 95, 'iso2' => 'GY', 'iso3' => 'GUY', 'name' => 'Guyana', 'numcode' => 328, 'region_id' => 26],
        ['id' => 96, 'iso2' => 'HT', 'iso3' => 'HTI', 'name' => 'Haiti', 'numcode' => 332, 'region_id' => 26],
        ['id' => 97, 'iso2' => 'HM', 'iso3' => 'HMD', 'name' => 'Heard Island and McDonald Islands', 'numcode' => 334, 'region_id' => NULL],
        ['id' => 98, 'iso2' => 'VA', 'iso3' => 'VAT', 'name' => 'Vatican', 'numcode' => 336, 'region_id' => 21],
        ['id' => 99, 'iso2' => 'HN', 'iso3' => 'HND', 'name' => 'Honduras', 'numcode' => 340, 'region_id' => 26],
        ['id' => 100, 'iso2' => 'HK', 'iso3' => 'HKG', 'name' => 'Hong Kong S.A.R., China', 'numcode' => 344, 'region_id' => 24],
        ['id' => 101, 'iso2' => 'HU', 'iso3' => 'HUN', 'name' => 'Hungary', 'numcode' => 348, 'region_id' => 21],
        ['id' => 102, 'iso2' => 'IS', 'iso3' => 'ISL', 'name' => 'Iceland', 'numcode' => 352, 'region_id' => 21],
        ['id' => 103, 'iso2' => 'IN', 'iso3' => 'IND', 'name' => 'India', 'numcode' => 356, 'region_id' => 8],
        ['id' => 104, 'iso2' => 'ID', 'iso3' => 'IDN', 'name' => 'Indonesia', 'numcode' => 360, 'region_id' => 24],
        ['id' => 105, 'iso2' => 'IR', 'iso3' => 'IRN', 'name' => 'Iran', 'numcode' => 364, 'region_id' => 13],
        ['id' => 106, 'iso2' => 'IQ', 'iso3' => 'IRQ', 'name' => 'Iraq', 'numcode' => 368, 'region_id' => 13],
        ['id' => 107, 'iso2' => 'IE', 'iso3' => 'IRL', 'name' => 'Ireland', 'numcode' => 372, 'region_id' => 21],
        ['id' => 108, 'iso2' => 'IM', 'iso3' => 'IMN', 'name' => 'Isle of Man', 'numcode' => 833, 'region_id' => 21],
        ['id' => 109, 'iso2' => 'IL', 'iso3' => 'ISR', 'name' => 'Israel', 'numcode' => 376, 'region_id' => 13],
        ['id' => 110, 'iso2' => 'IT', 'iso3' => 'ITA', 'name' => 'Italy', 'numcode' => 380, 'region_id' => 21],
        ['id' => 111, 'iso2' => 'JM', 'iso3' => 'JAM', 'name' => 'Jamaica', 'numcode' => 388, 'region_id' => 26],
        ['id' => 112, 'iso2' => 'JP', 'iso3' => 'JPN', 'name' => 'Japan', 'numcode' => 392, 'region_id' => 24],
        ['id' => 113, 'iso2' => 'JE', 'iso3' => 'JEY', 'name' => 'Jersey', 'numcode' => 832, 'region_id' => 21],
        ['id' => 114, 'iso2' => 'JO', 'iso3' => 'JOR', 'name' => 'Jordan', 'numcode' => 400, 'region_id' => 13],
        ['id' => 115, 'iso2' => 'KZ', 'iso3' => 'KAZ', 'name' => 'Kazakhstan', 'numcode' => 398, 'region_id' => 21],
        ['id' => 116, 'iso2' => 'KE', 'iso3' => 'KEN', 'name' => 'Kenya', 'numcode' => 404, 'region_id' => 47],
        ['id' => 117, 'iso2' => 'KI', 'iso3' => 'KIR', 'name' => 'Kiribati', 'numcode' => 296, 'region_id' => 24],
        ['id' => 118, 'iso2' => 'KP', 'iso3' => 'PRK', 'name' => 'North Korea', 'numcode' => 408, 'region_id' => 8],
        ['id' => 119, 'iso2' => 'KR', 'iso3' => 'KOR', 'name' => 'South Korea', 'numcode' => 410, 'region_id' => 8],
        ['id' => 120, 'iso2' => 'KW', 'iso3' => 'KWT', 'name' => 'Kuwait', 'numcode' => 414, 'region_id' => 13],
        ['id' => 121, 'iso2' => 'KG', 'iso3' => 'KGZ', 'name' => 'Kyrgyzstan', 'numcode' => 417, 'region_id' => 21],
        ['id' => 122, 'iso2' => 'LA', 'iso3' => 'LAO', 'name' => 'Laos PDR', 'numcode' => 418, 'region_id' => 24],
        ['id' => 123, 'iso2' => 'LV', 'iso3' => 'LVA', 'name' => 'Latvia', 'numcode' => 428, 'region_id' => 21],
        ['id' => 124, 'iso2' => 'LB', 'iso3' => 'LBN', 'name' => 'Lebanon', 'numcode' => 422, 'region_id' => 13],
        ['id' => 125, 'iso2' => 'LS', 'iso3' => 'LSO', 'name' => 'Lesotho', 'numcode' => 426, 'region_id' => 47],
        ['id' => 126, 'iso2' => 'LR', 'iso3' => 'LBR', 'name' => 'Liberia', 'numcode' => 430, 'region_id' => 47],
        ['id' => 127, 'iso2' => 'LY', 'iso3' => 'LBY', 'name' => 'Libya', 'numcode' => 434, 'region_id' => 13],
        ['id' => 128, 'iso2' => 'LI', 'iso3' => 'LIE', 'name' => 'Liechtenstein', 'numcode' => 438, 'region_id' => 21],
        ['id' => 129, 'iso2' => 'LT', 'iso3' => 'LTU', 'name' => 'Lithuania', 'numcode' => 440, 'region_id' => 21],
        ['id' => 130, 'iso2' => 'LU', 'iso3' => 'LUX', 'name' => 'Luxembourg', 'numcode' => 442, 'region_id' => 21],
        ['id' => 131, 'iso2' => 'MO', 'iso3' => 'MAC', 'name' => 'Macao S.A.R., China', 'numcode' => 446, 'region_id' => 24],
        ['id' => 132, 'iso2' => 'MK', 'iso3' => 'MKD', 'name' => 'Macedonia', 'numcode' => 807, 'region_id' => 21],
        ['id' => 133, 'iso2' => 'MG', 'iso3' => 'MDG', 'name' => 'Madagascar', 'numcode' => 450, 'region_id' => 47],
        ['id' => 134, 'iso2' => 'MW', 'iso3' => 'MWI', 'name' => 'Malawi', 'numcode' => 454, 'region_id' => 47],
        ['id' => 135, 'iso2' => 'MY', 'iso3' => 'MYS', 'name' => 'Malaysia', 'numcode' => 458, 'region_id' => 24],
        ['id' => 136, 'iso2' => 'MV', 'iso3' => 'MDV', 'name' => 'Maldives', 'numcode' => 462, 'region_id' => 8],
        ['id' => 137, 'iso2' => 'ML', 'iso3' => 'MLI', 'name' => 'Mali', 'numcode' => 466, 'region_id' => 47],
        ['id' => 138, 'iso2' => 'MT', 'iso3' => 'MLT', 'name' => 'Malta', 'numcode' => 470, 'region_id' => 13],
        ['id' => 139, 'iso2' => 'MH', 'iso3' => 'MHL', 'name' => 'Marshall Islands', 'numcode' => 584, 'region_id' => 24],
        ['id' => 140, 'iso2' => 'MQ', 'iso3' => 'MTQ', 'name' => 'Martinique', 'numcode' => 474, 'region_id' => 26],
        ['id' => 141, 'iso2' => 'MR', 'iso3' => 'MRT', 'name' => 'Mauritania', 'numcode' => 478, 'region_id' => 47],
        ['id' => 142, 'iso2' => 'MU', 'iso3' => 'MUS', 'name' => 'Mauritius', 'numcode' => 480, 'region_id' => 47],
        ['id' => 143, 'iso2' => 'YT', 'iso3' => 'MYT', 'name' => 'Mayotte', 'numcode' => 175, 'region_id' => 13],
        ['id' => 144, 'iso2' => 'MX', 'iso3' => 'MEX', 'name' => 'Mexico', 'numcode' => 484, 'region_id' => 26],
        ['id' => 145, 'iso2' => 'FM', 'iso3' => 'FSM', 'name' => 'Micronesia', 'numcode' => 583, 'region_id' => 24],
        ['id' => 146, 'iso2' => 'MD', 'iso3' => 'MDA', 'name' => 'Moldova', 'numcode' => 498, 'region_id' => 21],
        ['id' => 147, 'iso2' => 'MC', 'iso3' => 'MCO', 'name' => 'Monaco', 'numcode' => 492, 'region_id' => 21],
        ['id' => 148, 'iso2' => 'MN', 'iso3' => 'MNG', 'name' => 'Mongolia', 'numcode' => 496, 'region_id' => 24],
        ['id' => 149, 'iso2' => 'ME', 'iso3' => 'MNE', 'name' => 'Montenegro', 'numcode' => 499, 'region_id' => 21],
        ['id' => 150, 'iso2' => 'MS', 'iso3' => 'MSR', 'name' => 'Montserrat', 'numcode' => 500, 'region_id' => 26],
        ];

        $data2 = [['id' => 151, 'iso2' => 'MA', 'iso3' => 'MAR', 'name' => 'Morocco', 'numcode' => 504, 'region_id' => 13],
        ['id' => 152, 'iso2' => 'MZ', 'iso3' => 'MOZ', 'name' => 'Mozambique', 'numcode' => 508, 'region_id' => 47],
        ['id' => 153, 'iso2' => 'MM', 'iso3' => 'MMR', 'name' => 'Myanmar', 'numcode' => 104, 'region_id' => 24],
        ['id' => 154, 'iso2' => 'NA', 'iso3' => 'NAM', 'name' => 'Namibia', 'numcode' => 516, 'region_id' => 47],
        ['id' => 155, 'iso2' => 'NR', 'iso3' => 'NRU', 'name' => 'Nauru', 'numcode' => 520, 'region_id' => 24],
        ['id' => 156, 'iso2' => 'NP', 'iso3' => 'NPL', 'name' => 'Nepal', 'numcode' => 524, 'region_id' => 8],
        ['id' => 157, 'iso2' => 'NL', 'iso3' => 'NLD', 'name' => 'Netherlands', 'numcode' => 528, 'region_id' => 21],
        ['id' => 158, 'iso2' => 'AN', 'iso3' => 'ANT', 'name' => 'Netherlands Antilles', 'numcode' => 530, 'region_id' => 26],
        ['id' => 159, 'iso2' => 'NC', 'iso3' => 'NCL', 'name' => 'New Caledonia', 'numcode' => 540, 'region_id' => 24],
        ['id' => 160, 'iso2' => 'NZ', 'iso3' => 'NZL', 'name' => 'New Zealand', 'numcode' => 554, 'region_id' => 24],
        ['id' => 161, 'iso2' => 'NI', 'iso3' => 'NIC', 'name' => 'Nicaragua', 'numcode' => 558, 'region_id' => 26],
        ['id' => 162, 'iso2' => 'NE', 'iso3' => 'NER', 'name' => 'Niger', 'numcode' => 562, 'region_id' => 47],
        ['id' => 163, 'iso2' => 'NG', 'iso3' => 'NGA', 'name' => 'Nigeria', 'numcode' => 566, 'region_id' => 47],
        ['id' => 164, 'iso2' => 'NU', 'iso3' => 'NIU', 'name' => 'Niue', 'numcode' => 570, 'region_id' => 24],
        ['id' => 165, 'iso2' => 'NF', 'iso3' => 'NFK', 'name' => 'Norfolk Island', 'numcode' => 574, 'region_id' => 24],
        ['id' => 166, 'iso2' => 'MP', 'iso3' => 'MNP', 'name' => 'Northern Mariana Islands', 'numcode' => 580, 'region_id' => 24],
        ['id' => 167, 'iso2' => 'NO', 'iso3' => 'NOR', 'name' => 'Norway', 'numcode' => 578, 'region_id' => 21],
        ['id' => 168, 'iso2' => 'OM', 'iso3' => 'OMN', 'name' => 'Oman', 'numcode' => 512, 'region_id' => 13],
        ['id' => 169, 'iso2' => 'PK', 'iso3' => 'PAK', 'name' => 'Pakistan', 'numcode' => 586, 'region_id' => 8],
        ['id' => 170, 'iso2' => 'PW', 'iso3' => 'PLW', 'name' => 'Palau', 'numcode' => 585, 'region_id' => 24],
        ['id' => 171, 'iso2' => 'PS', 'iso3' => 'PSE', 'name' => 'Gaza Strip', 'numcode' => 275, 'region_id' => 8],
        ['id' => 172, 'iso2' => 'PA', 'iso3' => 'PAN', 'name' => 'Panama', 'numcode' => 591, 'region_id' => 26],
        ['id' => 173, 'iso2' => 'PG', 'iso3' => 'PNG', 'name' => 'Papua New Guinea', 'numcode' => 598, 'region_id' => 24],
        ['id' => 174, 'iso2' => 'PY', 'iso3' => 'PRY', 'name' => 'Paraguay', 'numcode' => 600, 'region_id' => 26],
        ['id' => 175, 'iso2' => 'PE', 'iso3' => 'PER', 'name' => 'Peru', 'numcode' => 604, 'region_id' => 26],
        ['id' => 176, 'iso2' => 'PH', 'iso3' => 'PHL', 'name' => 'Philippines', 'numcode' => 608, 'region_id' => 24],
        ['id' => 177, 'iso2' => 'PN', 'iso3' => 'PCN', 'name' => 'Pitcairn', 'numcode' => 612, 'region_id' => 24],
        ['id' => 178, 'iso2' => 'PL', 'iso3' => 'POL', 'name' => 'Poland', 'numcode' => 616, 'region_id' => 21],
        ['id' => 179, 'iso2' => 'PT', 'iso3' => 'PRT', 'name' => 'Portugal', 'numcode' => 620, 'region_id' => 21],
        ['id' => 180, 'iso2' => 'PR', 'iso3' => 'PRI', 'name' => 'Puerto Rico', 'numcode' => 630, 'region_id' => 26],
        ['id' => 181, 'iso2' => 'QA', 'iso3' => 'QAT', 'name' => 'Qatar', 'numcode' => 634, 'region_id' => 13],
        ['id' => 182, 'iso2' => 'RE', 'iso3' => 'REU', 'name' => 'Reunion', 'numcode' => 638, 'region_id' => 13],
        ['id' => 183, 'iso2' => 'RO', 'iso3' => 'ROU', 'name' => 'Romania', 'numcode' => 642, 'region_id' => 21],
        ['id' => 184, 'iso2' => 'RU', 'iso3' => 'RUS', 'name' => 'Russia', 'numcode' => 643, 'region_id' => 21],
        ['id' => 185, 'iso2' => 'RW', 'iso3' => 'RWA', 'name' => 'Rwanda', 'numcode' => 646, 'region_id' => 47],
        ['id' => 186, 'iso2' => 'BL', 'iso3' => 'BLM', 'name' => 'Saint Barthélemy', 'numcode' => 652, 'region_id' => 26],
        ['id' => 187, 'iso2' => 'SH', 'iso3' => 'SHN', 'name' => 'Saint Helena', 'numcode' => 654, 'region_id' => 13],
        ['id' => 188, 'iso2' => 'KN', 'iso3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'numcode' => 659, 'region_id' => 26],
        ['id' => 189, 'iso2' => 'LC', 'iso3' => 'LCA', 'name' => 'Saint Lucia', 'numcode' => 662, 'region_id' => 26],
        ['id' => 190, 'iso2' => 'MF', 'iso3' => 'MAF', 'name' => 'Saint Martin (French part)', 'numcode' => 663, 'region_id' => 26],
        ['id' => 191, 'iso2' => 'PM', 'iso3' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'numcode' => 666, 'region_id' => 26],
        ['id' => 192, 'iso2' => 'VC', 'iso3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'numcode' => 670, 'region_id' => 26],
        ['id' => 193, 'iso2' => 'WS', 'iso3' => 'WSM', 'name' => 'Samoa', 'numcode' => 882, 'region_id' => 24],
        ['id' => 194, 'iso2' => 'SM', 'iso3' => 'SMR', 'name' => 'San Marino', 'numcode' => 674, 'region_id' => 21],
        ['id' => 195, 'iso2' => 'ST', 'iso3' => 'STP', 'name' => 'Sao Tome and Principe', 'numcode' => 678, 'region_id' => 47],
        ['id' => 196, 'iso2' => 'SA', 'iso3' => 'SAU', 'name' => 'Saudi Arabia', 'numcode' => 682, 'region_id' => 13],
        ['id' => 197, 'iso2' => 'SN', 'iso3' => 'SEN', 'name' => 'Senegal', 'numcode' => 686, 'region_id' => 47],
        ['id' => 198, 'iso2' => 'RS', 'iso3' => 'SRB', 'name' => 'Serbia', 'numcode' => 688, 'region_id' => 21],
        ['id' => 199, 'iso2' => 'SC', 'iso3' => 'SYC', 'name' => 'Seychelles', 'numcode' => 690, 'region_id' => 47],
        ['id' => 200, 'iso2' => 'SL', 'iso3' => 'SLE', 'name' => 'Sierra Leone', 'numcode' => 694, 'region_id' => 47],
        ['id' => 201, 'iso2' => 'SG', 'iso3' => 'SGP', 'name' => 'Singapore', 'numcode' => 702, 'region_id' => 24],
        ['id' => 202, 'iso2' => 'SX', 'iso3' => 'SXM', 'name' => 'Sint Maarten (Dutch part)', 'numcode' => 534, 'region_id' => 26],
        ['id' => 203, 'iso2' => 'SK', 'iso3' => 'SVK', 'name' => 'Slovakia', 'numcode' => 703, 'region_id' => 21],
        ['id' => 204, 'iso2' => 'SI', 'iso3' => 'SVN', 'name' => 'Slovenia', 'numcode' => 705, 'region_id' => 21],
        ['id' => 205, 'iso2' => 'SB', 'iso3' => 'SLB', 'name' => 'Solomon Islands', 'numcode' => 90, 'region_id' => 24],
        ['id' => 206, 'iso2' => 'SO', 'iso3' => 'SOM', 'name' => 'Somalia', 'numcode' => 706, 'region_id' => 47],
        ['id' => 207, 'iso2' => 'ZA', 'iso3' => 'ZAF', 'name' => 'South Africa', 'numcode' => 710, 'region_id' => 47],
        ['id' => 208, 'iso2' => 'GS', 'iso3' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands', 'numcode' => 239, 'region_id' => NULL],
        ['id' => 209, 'iso2' => 'ES', 'iso3' => 'ESP', 'name' => 'Spain', 'numcode' => 724, 'region_id' => 21],
        ['id' => 210, 'iso2' => 'LK', 'iso3' => 'LKA', 'name' => 'Sri Lanka', 'numcode' => 144, 'region_id' => 8],
        ['id' => 211, 'iso2' => 'SS', 'iso3' => 'SSD', 'name' => 'South Sudan', 'numcode' => 728, 'region_id' => 47],
        ['id' => 212, 'iso2' => 'SD', 'iso3' => 'SDN', 'name' => 'Sudan', 'numcode' => 729, 'region_id' => 47],
        ['id' => 213, 'iso2' => 'SR', 'iso3' => 'SUR', 'name' => 'Suriname', 'numcode' => 740, 'region_id' => 26],
        ['id' => 214, 'iso2' => 'SJ', 'iso3' => 'SJM', 'name' => 'Svalbard and Jan Mayen', 'numcode' => 744, 'region_id' => 21],
        ['id' => 215, 'iso2' => 'SZ', 'iso3' => 'SWZ', 'name' => 'Swaziland', 'numcode' => 748, 'region_id' => 47],
        ['id' => 216, 'iso2' => 'SE', 'iso3' => 'SWE', 'name' => 'Sweden', 'numcode' => 752, 'region_id' => 21],
        ['id' => 217, 'iso2' => 'CH', 'iso3' => 'CHE', 'name' => 'Switzerland', 'numcode' => 756, 'region_id' => 21],
        ['id' => 218, 'iso2' => 'SY', 'iso3' => 'SYR', 'name' => 'Syria', 'numcode' => 760, 'region_id' => 13],
        ['id' => 219, 'iso2' => 'TW', 'iso3' => 'TWN', 'name' => 'Taiwan', 'numcode' => 158, 'region_id' => 24],
        ['id' => 220, 'iso2' => 'TJ', 'iso3' => 'TJK', 'name' => 'Tajikistan', 'numcode' => 762, 'region_id' => 21],
        ['id' => 221, 'iso2' => 'TZ', 'iso3' => 'TZA', 'name' => 'Tanzania', 'numcode' => 834, 'region_id' => 47],
        ['id' => 222, 'iso2' => 'TH', 'iso3' => 'THA', 'name' => 'Thailand', 'numcode' => 764, 'region_id' => 24],
        ['id' => 223, 'iso2' => 'TL', 'iso3' => 'TLS', 'name' => 'Timor-Leste', 'numcode' => 626, 'region_id' => 24],
        ['id' => 224, 'iso2' => 'TG', 'iso3' => 'TGO', 'name' => 'Togo', 'numcode' => 768, 'region_id' => 47],
        ['id' => 225, 'iso2' => 'TK', 'iso3' => 'TKL', 'name' => 'Tokelau', 'numcode' => 772, 'region_id' => 24],
        ['id' => 226, 'iso2' => 'TO', 'iso3' => 'TON', 'name' => 'Tonga', 'numcode' => 776, 'region_id' => 24],
        ['id' => 227, 'iso2' => 'TT', 'iso3' => 'TTO', 'name' => 'Trinidad and Tobago', 'numcode' => 780, 'region_id' => 26],
        ['id' => 228, 'iso2' => 'TN', 'iso3' => 'TUN', 'name' => 'Tunisia', 'numcode' => 788, 'region_id' => 13],
        ['id' => 229, 'iso2' => 'TR', 'iso3' => 'TUR', 'name' => 'Turkey', 'numcode' => 792, 'region_id' => 21],
        ['id' => 230, 'iso2' => 'TM', 'iso3' => 'TKM', 'name' => 'Turkmenistan', 'numcode' => 795, 'region_id' => 21],
        ['id' => 231, 'iso2' => 'TC', 'iso3' => 'TCA', 'name' => 'Turks and Caicos Islands', 'numcode' => 796, 'region_id' => 26],
        ['id' => 232, 'iso2' => 'TV', 'iso3' => 'TUV', 'name' => 'Tuvalu', 'numcode' => 798, 'region_id' => 24],
        ['id' => 233, 'iso2' => 'UG', 'iso3' => 'UGA', 'name' => 'Uganda', 'numcode' => 800, 'region_id' => 47],
        ['id' => 234, 'iso2' => 'UA', 'iso3' => 'UKR', 'name' => 'Ukraine', 'numcode' => 804, 'region_id' => 21],
        ['id' => 235, 'iso2' => 'AE', 'iso3' => 'ARE', 'name' => 'United Arab Emirates', 'numcode' => 784, 'region_id' => 13],
        ['id' => 236, 'iso2' => 'GB', 'iso3' => 'GBR', 'name' => 'United Kingdom', 'numcode' => 826, 'region_id' => 21],
        ['id' => 237, 'iso2' => 'US', 'iso3' => 'USA', 'name' => 'United States', 'numcode' => 840, 'region_id' => 26],
        ['id' => 238, 'iso2' => 'UM', 'iso3' => 'UMI', 'name' => 'United States Minor Outlying Islands', 'numcode' => 581, 'region_id' => 24],
        ['id' => 239, 'iso2' => 'UY', 'iso3' => 'URY', 'name' => 'Uruguay', 'numcode' => 858, 'region_id' => 26],
        ['id' => 240, 'iso2' => 'UZ', 'iso3' => 'UZB', 'name' => 'Uzbekistan', 'numcode' => 860, 'region_id' => 21],
        ['id' => 241, 'iso2' => 'VU', 'iso3' => 'VUT', 'name' => 'Vanuatu', 'numcode' => 548, 'region_id' => 24],
        ['id' => 242, 'iso2' => 'VE', 'iso3' => 'VEN', 'name' => 'Venezuela', 'numcode' => 862, 'region_id' => 26],
        ['id' => 243, 'iso2' => 'VN', 'iso3' => 'VNM', 'name' => 'Vietnam', 'numcode' => 704, 'region_id' => 24],
        ['id' => 244, 'iso2' => 'VG', 'iso3' => 'VGB', 'name' => 'British Virgin Islands', 'numcode' => 92, 'region_id' => 26],
        ['id' => 245, 'iso2' => 'VI', 'iso3' => 'VIR', 'name' => 'U.S. Virgin Islands', 'numcode' => 850, 'region_id' => 26],
        ['id' => 246, 'iso2' => 'WF', 'iso3' => 'WLF', 'name' => 'Wallis and Futuna', 'numcode' => 876, 'region_id' => 24],
        ['id' => 247, 'iso2' => 'EH', 'iso3' => 'ESH', 'name' => 'Western Sahara', 'numcode' => 732, 'region_id' => 47],
        ['id' => 248, 'iso2' => 'YE', 'iso3' => 'YEM', 'name' => 'Yemen', 'numcode' => 887, 'region_id' => 13],
        ['id' => 249, 'iso2' => 'ZM', 'iso3' => 'ZMB', 'name' => 'Zambia', 'numcode' => 894, 'region_id' => 47],
        ['id' => 250, 'iso2' => 'ZW', 'iso3' => 'ZWE', 'name' => 'Zimbabwe', 'numcode' => 716, 'region_id' => 47],
        ['id' => 251, 'iso2' => 'XK', 'iso3' => '', 'Kosovo', 'numcode' => 0, 'region_id' => 21]
    ];
        Country::insert($data1);
        Country::insert($data2);
    }
}
